export const HOME_ROUTE = '/'
export const ADMIN_ROUTE = '/admin'
export const CABINET_ROUTE = '/cabinet'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const TESTING_ROUTE = '/testing'
